name = "ConvexSampling"
uuid = "d885f151-cbab-467a-b201-f219b0eaf451"
authors = ["Kamil A. Khan <kamil@alum.mit.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
